services:
  app:
    build: .
    image: chisaelim/my-app:latest
    container_name: my-app-container
    volumes:
      - ./:/var/www/html
      - node:/var/www/html/node_modules
      - laravel:/var/www/html/vendor
    # command: sh /var/www/html/start.sh
    ports:
      - 8000:80
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PASSWORD: root
  mysql:
    image: mariadb:10.11.13
    container_name: mysql-my-app-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: UTC
    command: --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin:5.2.2
    container_name: phpmyadmin-my-app-container
    depends_on:
      - mysql
    environment:
      UPLOAD_LIMIT: 50M
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 8001:80
volumes:
  mysql:
    name: my-app-mysql
  node:
    name: my-app-node
  laravel:
    name: my-app-laravel